### ISSUE TITLE
MyUpdateTimer: CalledFromWrongThread

### ISSUE THREAD

**Issue by StephGit** [StephGit/EazyTime#60]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1083)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
        at android.view.View.invalidateInternal(View.java:13656)
        at android.view.View.invalidate(View.java:13620)
        at android.view.View.invalidate(View.java:13604)
        at android.widget.TextView.checkForRelayout(TextView.java:7347)
        at android.widget.TextView.setText(TextView.java:4480)
        at android.widget.TextView.setText(TextView.java:4337)
        at android.widget.TextView.setText(TextView.java:4312)
        at ch.bfh.mad.eazytime.projects.MyUpdateTimer.run(ProjectsRecycleListAdapter.kt:151)

- [x] API Level 25 Android 7.1.1
- [x] API Level 27 Android 8.0.0
- [x] API Level 28 Android 9.0.0

**Comment by StephGit** [comment]
mit api level 25 getestet
